apiVersion: standards.spyroot.dev/v1alpha1
kind: ProjectStandardsBinding
metadata:
  name: redfish_ctl
spec:
  source:
    localPath: /Users/spyroot/dev/standards
    repository: https://gitlab.rnd.embedings.ai/spyroot/standards.git
    revision: 033518d3f5aeda30e1d1a315382e0cedf2ca84cb
  requiredContracts:
    - ci
    - unit-testing
    - smoke-testing
    - blockers
    - agent-workspace
    - automation
    - project-consumer
  projectAdditions:
    - TEAM_GUIDE.md
  exceptions: []
